### ISSUE TITLE
开发者，注意升级到Trojan-gfw 1.13.0了，请更新适配，谢谢

### ISSUE THREAD

**Issue by fuyinhua** [KevinZonda/trojan-client-slim#1]

**Comment by KevinZonda** [comment]
Replace the updated trojan.exe may will work. I will update this weekend, maybe.

**Comment by KevinZonda** [comment]
Now update Trojan 1.12 -> 1.14 c732e78002c82fc54b7b66306e3ddef3b8fd4c14
TLS1.3 supported d6517548ea6ab825a3983ab1aed50cc8bfae485a
