### ISSUE TITLE
Anti-virus  block the apps. 

### ISSUE THREAD

**Issue by malikshi** [KevinZonda/trojan-client-slim#10]
Bitdefender block TCS. Is it fixed now?

**Comment by KevinZonda** [comment]
What kind of virus is reported?

**Comment by KevinZonda** [comment]
https://s.threatbook.cn/report/file/885ed928ceb1bbf4d1543717114057a12df7570e31fe840512838ff2f0418cfa/?sign=history&env=win7_sp1_enx86_office2013

**Comment by malikshi** [comment]
let me test first for new release, the old one are being blocked,

**Comment by malikshi** [comment]
ok, its fixed :O great app :) thanks @KevinZonda

**Comment by KevinZonda** [comment]
That's Okay :)
