### ISSUE TITLE
[feature]sni config

### ISSUE THREAD

**Issue by mem0rz** [KevinZonda/trojan-client-slim#11]
Would be nice to have a function to config SNI different to remote address

For example: U have 2 or more Trojan server use same domain cert and every server enable Nginx SNI Preread function.

Would be nicer if I can config remote address and domain name(SNI) separately so that I can easily assign a specific server without modifying hosts file.

**Comment by KevinZonda** [comment]
![Image](https://user-images.githubusercontent.com/33132228/76376491-61267f80-6383-11ea-8037-d637888ea29e.png)
Like this?

**Comment by KevinZonda** [comment]
> 
> 
> Would be nice to have a function to config SNI different to remote address
> 
> For example: U have 2 or more Trojan server use same domain cert and every server enable Nginx SNI Preread function.
> 
> Would be nicer if I can config remote address and domain name(SNI) separately so that I can easily assign a specific server without modifying hosts file.

@cybmp3 Like this?
![Image](https://user-images.githubusercontent.com/33132228/76376532-769ba980-6383-11ea-8261-99d52a754d02.png)

**Comment by mem0rz** [comment]
> 
> 
> > Would be nice to have a function to config SNI different to remote address
> > For example: U have 2 or more Trojan server use same domain cert and every server enable Nginx SNI Preread function.
> > Would be nicer if I can config remote address and domain name(SNI) separately so that I can easily assign a specific server without modifying hosts file.
> 
> @cybmp3 Like this?
> ![Image](https://user-images.githubusercontent.com/33132228/76376532-769ba980-6383-11ea-8261-99d52a754d02.png)

correct!!!
Thank you!

**Comment by KevinZonda** [comment]
Finished in 95b4bd6da79ce829633342603bd6a6c49b00445b
