### ISSUE TITLE
请问gfwlist.action文件能更新吗？

### ISSUE THREAD

**Issue by aglent** [KevinZonda/trojan-client-slim#12]
gfwlist.action应该是gfwlist文件 它会自动更新吗？

**Comment by KevinZonda** [comment]
> 
> 
> gfwlist.action应该是gfwlist文件 它会自动更新吗？

No. But you can use https://github.com/zfl9/gfwlist2privoxy to update it. Also, I recommand you that use GeoIP mode replace GFWList.

**Comment by aglent** [comment]
好 谢谢

**Comment by KevinZonda** [comment]
> 
> 
> 好 谢谢

And, I will update gfwlist recently, you can download the gfwlist.action after I update. :)
