### ISSUE TITLE
1

### ISSUE THREAD

**Issue by xt1085** [KevinZonda/trojan-client-slim#4]
1

**Comment by KevinZonda** [comment]
Good idea, but I think the official Telegram group is already good enough.

**Comment by KevinZonda** [comment]
So, r u a moto fan?😃

**Comment by xt1085** [comment]
haha yes

**Comment by KevinZonda** [comment]
me too

**Comment by xt1085** [comment]
建议包里放一个VC_redist.x64

**Comment by KevinZonda** [comment]
> 建议包里放一个VC_redist.x64

I will. And TG Group link is https://t.me/trojangfwcs
