### ISSUE TITLE
如何修改默认的1080端口？

### ISSUE THREAD

**Issue by aglent** [KevinZonda/trojan-client-slim#5]
我改了config.txt 但不管用

**Comment by KevinZonda** [comment]
The configuration file will be rebuilt automatically. I will develop a configuration manager in the near future.

**Comment by KevinZonda** [comment]
Add feature in 19dce5d81db907c9b9dc5722b0c671730fa87ce0.
In the next version, you can change it in config.ini(No settings provided yet).
