### ISSUE TITLE
希望添加保存节点功能

### ISSUE THREAD

**Issue by linkmyway** [KevinZonda/trojan-client-slim#7]
每次开机好像都要重新输入一遍域名端口密码
稍微有点麻烦
可以加入保存的功能嘛 
谢谢🙏

**Comment by KevinZonda** [comment]
Autosave already exists. It will be saved automatically after clicking the start button.

**Comment by linkmyway** [comment]
这样嘛。。
不好意思哈
我再去试一下😳
