### ISSUE TITLE
Could you please make the autorun option

### ISSUE THREAD

**Issue by dayue1984** [KevinZonda/trojan-client-slim#9]
Need autorun function to start TCS on windows login, thanks!

**Comment by KevinZonda** [comment]
Good idea, will do in v2.4.0. Coming soon, haha~

**Comment by KevinZonda** [comment]
Do you think it is necessary to start the Trojan & etc. with the TCS?

**Comment by dayue1984** [comment]
> Do you think it is necessary to start the Trojan & etc. with the TCS?

Yeah, it's very necessary for me. It's a convenience option, so we don't need to cilck and hide TCS very time when we login to windows.

**Comment by KevinZonda** [comment]
Silence mode finished in d4ba207b413f64917db109d2d68dfaed89db6957
Run when startup: WIP

**Comment by KevinZonda** [comment]
Finished in 3a1a5e9.
Now you can download the latest version which supported that run when startup in RELEASE page.
